// SPDX-License-Identifier: GPL-3.0-or-later

//! The desktop's own colours, where the desktop publishes them (FEAT-080).
//!
//! Omarchy keeps the active theme as files on disk, and every other application
//! on the machine — the terminal, the editor, the bar — already follows them.
//! Spagitty was the window that did not match. This module is the whole of the
//! reading side: find the palette, parse it, validate it, hand back a typed
//! answer, and say when it changes.
//!
//! # What this module deliberately does not do
//!
//! **It does not decide what anything looks like.** It returns the desktop's
//! own semantic roles — background, foreground, accent, the status hues — and
//! nothing else. Turning those into Spagitty's fourteen tokens is a design
//! decision with contrast arithmetic in it, and it lives beside the other
//! palettes in `src/lib/omarchy.ts` where `themes.test.ts` can hold it to the
//! same ratios as the built-in families. Splitting it the other way would put
//! colour design in Rust and leave the frontend unable to check it.
//!
//! **It does not expose a path.** The frontend cannot ask this module to read
//! an arbitrary file; it can ask "what is the desktop's palette", and gets a
//! validated struct or nothing. A general "read this file" command reachable
//! from the webview would be a much larger thing to have built than a theme.
//!
//! **It does not source or execute anything.** Omarchy's theme directory also
//! holds `hyprland.lua`, `gum_env.lua`, `neovim.lua` and a `vscode-theme.json`.
//! Only `colors.toml` is read, and only as data.
//!
//! # Finding it
//!
//! Two layouts, because Omarchy moved and installations lag:
//!
//! | Layout  | Palette | Name |
//! |---------|---------|------|
//! | state   | `$XDG_STATE_HOME/omarchy/current/theme/colors.toml` | `current/theme.name` |
//! | legacy  | `$XDG_CONFIG_HOME/omarchy/current/theme/colors.toml` | the `current/theme` symlink's target |
//!
//! `$XDG_STATE_HOME` defaults to `~/.local/state` and `$XDG_CONFIG_HOME` to
//! `~/.config`, which is what Omarchy's own scripts use. The machine this was
//! written on has the state layout and no `~/.config/omarchy` at all.
//!
//! Detection is **evidence, not inference**. `XDG_CURRENT_DESKTOP=Hyprland` is
//! not proof of Omarchy — plenty of Hyprland installations are not Omarchy, and
//! Omarchy under a different session would be missed. What counts is an
//! Omarchy-shaped state or config directory *and* a palette in it that parses.
//! A directory with no usable palette is reported as not available rather than
//! as a broken Omarchy, because from Spagitty's side those are the same thing.
//!
//! # Why the parser is written here rather than pulled in
//!
//! `colors.toml` is generated by `omarchy-themes` and is a flat list of
//! `key = "value"` pairs with comments. It has no tables, no arrays, no
//! datetimes, no multi-line strings and no nesting. A TOML crate would parse a
//! language where this file is a sentence, and it would be a new direct
//! dependency in the binary to do it — which Amendment's forbidden-changes rule
//! asks to be justified rather than assumed.
//!
//! So the scanner below reads exactly that sentence: top-level quoted scalars,
//! a bounded number of them, from a bounded number of bytes, stopping dead at
//! the first `[table]` header so that a future file which *does* grow sections
//! is under-read rather than mis-read. It is about forty lines and every one of
//! its refusals is a test.
//!
//! # Watching
//!
//! `omarchy-theme-set` does not edit `colors.toml`. It builds a `next-theme`
//! directory and **replaces** `current/theme`, so a watch on the palette file's
//! own inode sees the first change and nothing after it. The watch is therefore
//! on the stable parent — `current`, and the directory above it — and the
//! palette is re-read from the path each time.

use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::sync::mpsc::{channel, Receiver, RecvTimeoutError, Sender};
use std::sync::Mutex;
use std::thread::JoinHandle;
use std::time::Duration;

use notify::{RecursiveMode, Watcher};
use serde::Serialize;
use tauri::{AppHandle, Emitter, Manager, Runtime, State};

/// Emitted when the desktop's palette has changed under us.
pub const THEME_CHANGED_EVENT: &str = "desktop-theme-changed";

/// The most of `colors.toml` that will ever be read.
///
/// The real file is about 1.3 KiB. This is not a performance limit — it is the
/// answer to "what if this path is a 4 GiB file or a fifo", which is a question
/// worth having an answer to for any path the application did not write.
const MAX_PALETTE_BYTES: u64 = 64 * 1024;

/// The most keys that will be kept from one file.
const MAX_KEYS: usize = 256;

/// The longest value that can be a colour. `color-mix(...)` is nowhere near it.
const MAX_VALUE_LEN: usize = 200;

/// A theme change is several filesystem events; coalesce them, as `watch` does.
const QUIET_PERIOD: Duration = Duration::from_millis(200);

/// Which layout the palette was found in. Reported so a bug report can say.
#[derive(Serialize, Clone, Copy, PartialEq, Eq, Debug)]
#[serde(rename_all = "camelCase")]
pub enum Layout {
    /// `$XDG_STATE_HOME/omarchy` — what current Omarchy uses.
    State,
    /// `$XDG_CONFIG_HOME/omarchy` — the older location.
    Legacy,
}

/// The desktop's palette, in the desktop's own vocabulary.
///
/// Every field is optional except the two that make a palette a palette,
/// because a theme generator is free to omit any of them and a half-read file
/// must not become a half-painted application. What the frontend does with the
/// gaps — derive, fall back to an ANSI slot, or refuse — is its decision, and
/// the shape of this struct is what lets it make one.
#[derive(Serialize, Clone, PartialEq, Eq, Debug, Default)]
#[serde(rename_all = "camelCase")]
pub struct DesktopPalette {
    /// `dark` or `light`, from the file's own `mode` where it has one.
    pub mode: Option<String>,
    pub background: String,
    pub foreground: String,
    pub accent: Option<String>,
    /// A step down from the background — window chrome.
    pub dark_bg: Option<String>,
    /// A step up from it — a raised surface.
    pub lighter_bg: Option<String>,
    /// The desktop's own idea of secondary text. **Often unreadable**: on the
    /// palette this was written against it is 2.75:1 on the background, so the
    /// frontend derives its own and keeps this for hue only.
    pub muted: Option<String>,
    pub selection_background: Option<String>,
    pub selection_foreground: Option<String>,
    /// Semantic hues, where the generator names them.
    pub red: Option<String>,
    pub green: Option<String>,
    pub yellow: Option<String>,
    pub blue: Option<String>,
    pub magenta: Option<String>,
    pub cyan: Option<String>,
    /// ANSI slots 0-15, as compatibility fallbacks for the hues above.
    pub ansi: Vec<Option<String>>,
}

/// What the frontend gets back, whether or not there is anything to follow.
#[derive(Serialize, Clone, PartialEq, Eq, Debug, Default)]
#[serde(rename_all = "camelCase")]
pub struct DesktopTheme {
    /// True only with a usable palette. The option in Settings keys off this.
    pub available: bool,
    /// The desktop's name for what is on — `sushi-dark-palette`.
    pub name: Option<String>,
    pub layout: Option<Layout>,
    pub palette: Option<DesktopPalette>,
    /// Why not, when `available` is false. For the Appearance screen's quiet
    /// status line, and for a bug report. Never a path the user did not give.
    pub reason: Option<String>,
}

impl DesktopTheme {
    fn unavailable(reason: &str) -> Self {
        Self {
            reason: Some(reason.to_string()),
            ..Default::default()
        }
    }
}

// --- Parsing --------------------------------------------------------------

/// Whether `value` is shaped like a colour this application may write into CSS.
///
/// The palette file is not hostile, but it is not ours either: it is generated
/// by another program, on a schedule nobody here controls, and its contents end
/// up as custom property values on the root element. So the check is a
/// whitelist of shapes rather than a blacklist of characters — a hex triple or
/// quad, in either case, with or without the `#`.
///
/// Deliberately narrower than CSS allows. Omarchy writes `#rrggbb` and nothing
/// else; accepting `rgb()` and named colours as well would widen the surface
/// for no file that exists.
fn is_colour(value: &str) -> bool {
    let hex = value.strip_prefix('#').unwrap_or(value);
    matches!(hex.len(), 3 | 4 | 6 | 8) && hex.chars().all(|c| c.is_ascii_hexdigit())
}

/// Normalise a colour to `#rrggbb`-style, so the frontend never sees two
/// spellings of the same value.
fn colour(value: &str) -> Option<String> {
    if !is_colour(value) {
        return None;
    }
    let hex = value.strip_prefix('#').unwrap_or(value);
    Some(format!("#{}", hex.to_ascii_lowercase()))
}

/// Read the flat top-level scalars out of a generated TOML file.
///
/// Everything this does *not* do is the point:
///
/// - it stops at the first `[section]` header, so a file that grows tables
///   later is read as far as it is understood and no further;
/// - it ignores anything that is not `key = "value"` or `key = 'value'`,
///   including bare numbers and booleans, which no colour is;
/// - it takes at most [`MAX_KEYS`] pairs and drops values over
///   [`MAX_VALUE_LEN`];
/// - it never unescapes, because a colour has no escapes and a parser that
///   handles `\u` is a parser with a bug in it waiting.
fn scan(text: &str) -> HashMap<String, String> {
    let mut out = HashMap::new();

    for line in text.lines() {
        if out.len() >= MAX_KEYS {
            break;
        }

        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        // A table header. Everything after it is nested, and nothing here
        // knows how to say so.
        if line.starts_with('[') {
            break;
        }

        let Some((key, rest)) = line.split_once('=') else {
            continue;
        };
        let key = key.trim();
        if key.is_empty() || !key.chars().all(|c| c.is_ascii_alphanumeric() || c == '_') {
            continue;
        }

        // The value, up to a trailing comment. Comments are only stripped
        // *outside* the quotes, which is why the quoted span is taken first.
        let rest = rest.trim();
        let quote = match rest.chars().next() {
            Some(c @ ('"' | '\'')) => c,
            // Unquoted: a number, a boolean, a date. Not a colour.
            _ => continue,
        };
        let Some(end) = rest[1..].find(quote) else {
            continue;
        };
        let value = &rest[1..1 + end];

        if value.len() > MAX_VALUE_LEN {
            continue;
        }
        out.insert(key.to_string(), value.to_string());
    }

    out
}

/// Build the typed palette from the scanned pairs, or nothing.
///
/// Two fields are required — a background and a foreground — because a palette
/// missing either is not a palette anybody could paint with, and reporting it
/// as available would mean Spagitty following a desktop into an unreadable
/// window. Everything else is optional and derived on the other side.
fn palette_from(pairs: &HashMap<String, String>) -> Option<DesktopPalette> {
    let pick = |names: &[&str]| -> Option<String> {
        names
            .iter()
            .find_map(|name| pairs.get(*name).and_then(|value| colour(value)))
    };

    let background = pick(&["background", "bg"])?;
    let foreground = pick(&["foreground", "fg"])?;

    // 0-15, each present or not. A gap is kept as a gap rather than closed up,
    // because slot 4 means blue and slot 5 means magenta — an ANSI palette is
    // positional and compacting it would silently recolour the graph.
    let ansi = (0..16)
        .map(|index| pairs.get(&format!("color{index}")).and_then(|v| colour(v)))
        .collect();

    let mode = pairs
        .get("mode")
        .and_then(|value| matches!(value.as_str(), "dark" | "light").then(|| value.to_string()));

    Some(DesktopPalette {
        mode,
        background,
        foreground,
        accent: pick(&["accent", "selection"]),
        dark_bg: pick(&["dark_bg", "darker_bg"]),
        lighter_bg: pick(&["lighter_bg"]),
        muted: pick(&["muted"]),
        selection_background: pick(&["selection_background"]),
        selection_foreground: pick(&["selection_foreground"]),
        red: pick(&["red"]),
        green: pick(&["green"]),
        yellow: pick(&["yellow"]),
        blue: pick(&["blue"]),
        magenta: pick(&["magenta"]),
        cyan: pick(&["cyan"]),
        ansi,
    })
}

// --- Finding it -----------------------------------------------------------

/// `$XDG_STATE_HOME`, or the default every Omarchy script uses.
fn state_home(env: &dyn Fn(&str) -> Option<String>) -> Option<PathBuf> {
    if let Some(explicit) = env("XDG_STATE_HOME").filter(|value| !value.is_empty()) {
        return Some(PathBuf::from(explicit));
    }
    Some(PathBuf::from(env("HOME")?).join(".local/state"))
}

/// `$XDG_CONFIG_HOME`, or its default.
fn config_home(env: &dyn Fn(&str) -> Option<String>) -> Option<PathBuf> {
    if let Some(explicit) = env("XDG_CONFIG_HOME").filter(|value| !value.is_empty()) {
        return Some(PathBuf::from(explicit));
    }
    Some(PathBuf::from(env("HOME")?).join(".config"))
}

/// The two roots to try, newest layout first.
///
/// Pure and taking its environment as a function, so the table of cases is a
/// test rather than a claim about the machine this was written on.
pub fn roots(env: &dyn Fn(&str) -> Option<String>) -> Vec<(Layout, PathBuf)> {
    let mut out = Vec::new();
    if let Some(path) = state_home(env) {
        out.push((Layout::State, path.join("omarchy")));
    }
    if let Some(path) = config_home(env) {
        out.push((Layout::Legacy, path.join("omarchy")));
    }
    out
}

/// Where the palette lives under a root, and where the name does.
fn palette_path(root: &Path) -> PathBuf {
    root.join("current/theme/colors.toml")
}

/// The theme's own name.
///
/// `theme.name` is what current Omarchy writes. The older layout has no such
/// file and instead makes `current/theme` a symlink into the themes directory,
/// so the link's target names the theme. Both are tried; neither is required,
/// because a nameless palette is still a palette.
fn theme_name(root: &Path) -> Option<String> {
    let named = root.join("current/theme.name");
    if let Ok(text) = std::fs::read_to_string(&named) {
        let name = text.trim();
        // A name is a label in a settings screen, not a path. Anything with a
        // separator in it is not one.
        if !name.is_empty() && name.len() <= 64 && !name.contains(['/', '\\', '\n']) {
            return Some(name.to_string());
        }
    }

    std::fs::read_link(root.join("current/theme"))
        .ok()?
        .file_name()?
        .to_str()
        .map(|name| name.to_string())
}

/// Read a file, refusing anything that is not a bounded regular file.
fn read_bounded(path: &Path) -> Option<String> {
    let meta = std::fs::metadata(path).ok()?;
    if !meta.is_file() || meta.len() > MAX_PALETTE_BYTES {
        return None;
    }
    std::fs::read_to_string(path).ok()
}

/// What the desktop is currently painted with, if anything.
///
/// Takes its environment so the whole search is testable against a temporary
/// directory rather than against whoever's machine runs the suite.
pub fn detect(env: &dyn Fn(&str) -> Option<String>) -> DesktopTheme {
    if !cfg!(target_os = "linux") {
        return DesktopTheme::unavailable("Omarchy is a Linux desktop");
    }

    let candidates = roots(env);
    if candidates.is_empty() {
        return DesktopTheme::unavailable("no home directory to look in");
    }

    let mut found_root = false;
    for (layout, root) in candidates {
        if !root.is_dir() {
            continue;
        }
        found_root = true;

        let Some(text) = read_bounded(&palette_path(&root)) else {
            continue;
        };
        let Some(palette) = palette_from(&scan(&text)) else {
            continue;
        };

        return DesktopTheme {
            available: true,
            name: theme_name(&root),
            layout: Some(layout),
            palette: Some(palette),
            reason: None,
        };
    }

    // The two cases are worth telling apart in a status line: one is "you are
    // not running Omarchy", the other is "you are, and its palette is not
    // readable", and only the second is worth reporting to anybody.
    DesktopTheme::unavailable(if found_root {
        "Omarchy is installed but its active palette could not be read"
    } else {
        "Omarchy was not detected"
    })
}

// --- Watching -------------------------------------------------------------

/// Holds the watcher alive. Dropping it stops watching and joins the thread.
pub struct ThemeWatcher {
    _watcher: notify::RecommendedWatcher,
    stop: Sender<()>,
    handle: Option<JoinHandle<()>>,
}

impl Drop for ThemeWatcher {
    fn drop(&mut self) {
        let _ = self.stop.send(());
        if let Some(handle) = self.handle.take() {
            let _ = handle.join();
        }
    }
}

/// The watcher, when one is running. Managed state, so the command layer can
/// start and stop it without the frontend holding a handle.
#[derive(Default)]
pub struct DesktopState {
    watcher: Mutex<Option<ThemeWatcher>>,
}

fn environment(name: &str) -> Option<String> {
    std::env::var(name).ok()
}

/// Start watching for a theme change, replacing any watch already running.
///
/// **The watch is on the directory, not the file.** `omarchy-theme-set` builds
/// a `next-theme` directory and replaces `current/theme` wholesale, so a
/// watcher registered against `colors.toml` follows an inode that stops being
/// the current palette after the first change — it would work once, in testing,
/// and then never again.
///
/// Two registrations, then: `current` recursively, which is small and is where
/// the replacement happens, and the root itself non-recursively, in case
/// `current` is what gets replaced.
fn start<R: Runtime>(app: AppHandle<R>) -> Option<ThemeWatcher> {
    let (layout_root, _) = roots(&environment)
        .into_iter()
        .find(|(_, root)| root.is_dir())
        .map(|(layout, root)| (root, layout))?;

    let (event_tx, event_rx) = channel::<notify::Result<notify::Event>>();
    let (stop_tx, stop_rx) = channel::<()>();

    let mut watcher = notify::recommended_watcher(move |res| {
        let _ = event_tx.send(res);
    })
    .ok()?;

    // Either registration may fail — `current` might not exist yet on a fresh
    // install — and one is enough to notice a change, so neither is fatal.
    let current = layout_root.join("current");
    let watched = watcher.watch(&current, RecursiveMode::Recursive).is_ok()
        | watcher
            .watch(&layout_root, RecursiveMode::NonRecursive)
            .is_ok();
    if !watched {
        return None;
    }

    let handle = std::thread::Builder::new()
        .name("spagitty-desktop-theme".into())
        .spawn(move || debounce(app, event_rx, stop_rx))
        .ok()?;

    Some(ThemeWatcher {
        _watcher: watcher,
        stop: stop_tx,
        handle: Some(handle),
    })
}

/// Coalesce a burst of events into one re-read, and emit only real changes.
///
/// The last valid palette is kept and compared against, for two reasons. A
/// theme switch touches a directory of twenty files and would otherwise emit
/// twenty times; and a *partial* update — the moment after the old directory
/// has gone and before the new one is in place — reads as unavailable, which
/// would blank the application's colours for a frame in the middle of a theme
/// change. An unreadable read is therefore dropped rather than reported, and
/// the palette that was last valid stays on screen until a new valid one
/// arrives.
fn debounce<R: Runtime>(
    app: AppHandle<R>,
    events: Receiver<notify::Result<notify::Event>>,
    stop: Receiver<()>,
) {
    let mut last = detect(&environment);

    loop {
        if stop.try_recv().is_ok() {
            return;
        }

        match events.recv_timeout(Duration::from_millis(250)) {
            Ok(_) => {}
            Err(RecvTimeoutError::Timeout) => continue,
            Err(RecvTimeoutError::Disconnected) => return,
        }

        // Keep draining until it goes quiet. A disconnected channel means the
        // watcher has been dropped, and there is nothing left to report to.
        if drain(&events) == RecvTimeoutError::Disconnected {
            return;
        }

        let next = detect(&environment);

        // Mid-replacement. Hold what we have; another event is coming.
        if !next.available && last.available {
            continue;
        }
        if next == last {
            continue;
        }

        last = next.clone();
        let _ = app.emit(THEME_CHANGED_EVENT, next);
    }
}

/// Wait out the quiet period, swallowing whatever arrives during it.
///
/// Returns why it stopped: `Timeout` is the theme change having finished, and
/// `Disconnected` is the watcher having been dropped out from under us.
fn drain(events: &Receiver<notify::Result<notify::Event>>) -> RecvTimeoutError {
    loop {
        match events.recv_timeout(QUIET_PERIOD) {
            Ok(_) => continue,
            Err(error) => return error,
        }
    }
}

// --- Commands -------------------------------------------------------------

/// Register the desktop state. Called once, from `run`.
pub fn manage<R: Runtime>(app: &AppHandle<R>) {
    app.manage(DesktopState::default());
}

/// What the desktop is painted with right now.
#[tauri::command]
pub fn desktop_theme() -> DesktopTheme {
    detect(&environment)
}

/// Start telling the frontend when it changes.
///
/// Idempotent: called again, it replaces the watch rather than adding one.
/// Returns whether a watch is running, which is not the same question as
/// whether a palette was found — a machine can have Omarchy and an inotify
/// limit already exhausted, and the answer there is "the theme works, live
/// updates do not", which the Appearance screen can say.
#[tauri::command]
pub fn desktop_theme_watch<R: Runtime>(app: AppHandle<R>, state: State<'_, DesktopState>) -> bool {
    let mut slot = state.watcher.lock().expect("desktop watcher");
    // Dropped first, so the old thread is joined before a new one starts and
    // two watchers never emit into the same window.
    *slot = None;
    *slot = start(app);
    slot.is_some()
}

/// Stop watching. Called when the user picks a theme source that is not the
/// desktop, and when the window goes away.
#[tauri::command]
pub fn desktop_theme_unwatch(state: State<'_, DesktopState>) {
    *state.watcher.lock().expect("desktop watcher") = None;
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::TempDir;

    /// The real file from the machine this was written on, trimmed to the
    /// shapes that matter. Using the genuine article rather than an invented
    /// one is the point: a parser tested only against its author's idea of the
    /// format is a parser tested against itself.
    const REAL: &str = r##"
# Generated by omarchy-themes. Semantic names mirror Omarchy's
# theme color system; color0-15 ANSI slots are kept for tools that
# still read them.
mode = "dark"

# UI Colors (extended)
accent = "#cf6348"
cursor = "#fcfcfd"

# Primary colors
foreground = "#fcfcfd"
background = "#191724"

# Selection colors
selection_foreground = "#191724"
selection_background = "#cf6348"

# Background shades
bg = "#191724"
lighter_bg = "#2a2735"
dark_bg = "#13101e"
darker_bg = "#0c0618"

# Foreground shades
fg = "#fcfcfd"
muted = "#5f5e63"

# Accent hues
red = "#bda8a4"
green = "#8fa487"
yellow = "#cd9071"
blue = "#778291"
magenta = "#a1758a"
cyan = "#4a89a4"

# Normal colors (ANSI 0-7)
color0 = "#1d1b28"
color1 = "#bda8a4"
color7 = "#dfdfe0"
"##;

    #[test]
    fn reads_the_real_file() {
        let palette = palette_from(&scan(REAL)).expect("a palette");

        assert_eq!(palette.background, "#191724");
        assert_eq!(palette.foreground, "#fcfcfd");
        assert_eq!(palette.accent.as_deref(), Some("#cf6348"));
        assert_eq!(palette.dark_bg.as_deref(), Some("#13101e"));
        assert_eq!(palette.lighter_bg.as_deref(), Some("#2a2735"));
        assert_eq!(palette.mode.as_deref(), Some("dark"));
        assert_eq!(palette.cyan.as_deref(), Some("#4a89a4"));
    }

    /// An ANSI palette is positional: slot 4 is blue and slot 5 is magenta. A
    /// gap has to stay a gap, or a partial file silently recolours the graph.
    #[test]
    fn keeps_ansi_slots_in_their_places() {
        let palette = palette_from(&scan(REAL)).unwrap();

        assert_eq!(palette.ansi.len(), 16);
        assert_eq!(palette.ansi[0].as_deref(), Some("#1d1b28"));
        assert_eq!(palette.ansi[1].as_deref(), Some("#bda8a4"));
        assert_eq!(palette.ansi[2], None, "color2 is absent from this fixture");
        assert_eq!(palette.ansi[7].as_deref(), Some("#dfdfe0"));
    }

    /// A palette without a ground or a text colour is not one, and reporting it
    /// as available would mean following a desktop into an unreadable window.
    #[test]
    fn refuses_a_file_with_no_ground_or_no_text() {
        assert!(palette_from(&scan("foreground = \"#ffffff\"")).is_none());
        assert!(palette_from(&scan("background = \"#000000\"")).is_none());
        assert!(palette_from(&scan("")).is_none());
    }

    #[test]
    fn falls_back_to_the_short_names() {
        let palette = palette_from(&scan("bg = \"#101010\"\nfg = \"#f0f0f0\"")).unwrap();
        assert_eq!(palette.background, "#101010");
        assert_eq!(palette.foreground, "#f0f0f0");
    }

    /// Everything the scanner is allowed to ignore, in one place.
    #[test]
    fn ignores_what_it_does_not_understand() {
        let pairs = scan(
            r##"
# a comment
background = "#101010"
count = 12
enabled = true
spaced   =    "#202020"
weird key = "#303030"
foreground = '#f0f0f0'
"##,
        );

        assert_eq!(pairs.get("background").map(String::as_str), Some("#101010"));
        assert_eq!(pairs.get("spaced").map(String::as_str), Some("#202020"));
        // Single quotes are TOML literal strings and a generator may use them.
        assert_eq!(pairs.get("foreground").map(String::as_str), Some("#f0f0f0"));
        // Not strings, so not colours.
        assert!(!pairs.contains_key("count"));
        assert!(!pairs.contains_key("enabled"));
        // Not a bare key.
        assert!(!pairs.contains_key("weird key"));
    }

    /// The one thing a flat scanner must not do: read a nested key as a top
    /// level one. Under-reading a file that grew sections is recoverable;
    /// mis-reading it paints the wrong colours and looks like it worked.
    #[test]
    fn stops_dead_at_a_table_header() {
        let pairs = scan(
            r##"
background = "#101010"
foreground = "#f0f0f0"

[terminal]
background = "#ff0000"
"##,
        );

        assert_eq!(pairs.get("background").map(String::as_str), Some("#101010"));
        assert_eq!(pairs.len(), 2);
    }

    #[test]
    fn refuses_values_that_are_not_colours() {
        assert!(colour("#191724").is_some());
        assert!(colour("191724").is_some());
        assert!(colour("#fff").is_some());
        assert!(colour("#191724ff").is_some());

        for bad in [
            "url(http://elsewhere/x.png)",
            "red",
            "#19172",
            "#gggggg",
            "rgb(1,2,3)",
            "",
            "#191724; content: 'no'",
        ] {
            assert!(colour(bad).is_none(), "{bad:?} should not be a colour");
        }
    }

    #[test]
    fn normalises_case_and_the_missing_hash() {
        assert_eq!(colour("#CF6348").as_deref(), Some("#cf6348"));
        assert_eq!(colour("CF6348").as_deref(), Some("#cf6348"));
    }

    #[test]
    fn drops_a_value_too_long_to_be_a_colour() {
        let long = "x".repeat(MAX_VALUE_LEN + 1);
        let pairs = scan(&format!("background = \"{long}\""));
        assert!(pairs.is_empty());
    }

    #[test]
    fn keeps_no_more_than_the_cap() {
        let text: String = (0..MAX_KEYS + 50)
            .map(|index| format!("key{index} = \"#000000\"\n"))
            .collect();
        assert_eq!(scan(&text).len(), MAX_KEYS);
    }

    /// The environment decides, and the defaults are the ones Omarchy's own
    /// scripts use — not `dirs`' opinion of them, and not this machine's.
    #[test]
    fn looks_in_the_state_directory_first_and_the_old_one_after() {
        let env = |name: &str| match name {
            "HOME" => Some("/home/somebody".to_string()),
            _ => None,
        };
        let found = roots(&env);

        assert_eq!(
            found,
            vec![
                (
                    Layout::State,
                    PathBuf::from("/home/somebody/.local/state/omarchy")
                ),
                (
                    Layout::Legacy,
                    PathBuf::from("/home/somebody/.config/omarchy")
                ),
            ]
        );
    }

    #[test]
    fn honours_the_xdg_variables_when_they_are_set() {
        let env = |name: &str| match name {
            "HOME" => Some("/home/somebody".to_string()),
            "XDG_STATE_HOME" => Some("/state".to_string()),
            "XDG_CONFIG_HOME" => Some("/config".to_string()),
            _ => None,
        };

        assert_eq!(
            roots(&env),
            vec![
                (Layout::State, PathBuf::from("/state/omarchy")),
                (Layout::Legacy, PathBuf::from("/config/omarchy")),
            ]
        );
    }

    /// An empty variable is not a value. Several shells export one by accident.
    #[test]
    fn treats_an_empty_xdg_variable_as_unset() {
        let env = |name: &str| match name {
            "HOME" => Some("/home/somebody".to_string()),
            "XDG_STATE_HOME" => Some(String::new()),
            _ => None,
        };

        assert_eq!(
            roots(&env)[0].1,
            PathBuf::from("/home/somebody/.local/state/omarchy")
        );
    }

    /// Build a state-layout Omarchy under a temporary directory.
    fn install(home: &Path, theme: &str, palette: &str) {
        let root = home.join(".local/state/omarchy/current/theme");
        fs::create_dir_all(&root).unwrap();
        fs::write(root.join("colors.toml"), palette).unwrap();
        fs::write(
            home.join(".local/state/omarchy/current/theme.name"),
            format!("{theme}\n"),
        )
        .unwrap();
    }

    fn env_for(home: &Path) -> impl Fn(&str) -> Option<String> + '_ {
        move |name: &str| match name {
            "HOME" => Some(home.to_string_lossy().into_owned()),
            _ => None,
        }
    }

    #[test]
    #[cfg(target_os = "linux")]
    fn finds_an_installed_theme_and_names_it() {
        let dir = TempDir::new().unwrap();
        install(dir.path(), "sushi-dark-palette", REAL);

        let found = detect(&env_for(dir.path()));

        assert!(found.available);
        assert_eq!(found.name.as_deref(), Some("sushi-dark-palette"));
        assert_eq!(found.layout, Some(Layout::State));
        assert_eq!(found.palette.unwrap().accent.as_deref(), Some("#cf6348"));
    }

    /// `XDG_CURRENT_DESKTOP=Hyprland` is not evidence and neither is an empty
    /// home. Nothing is available unless a palette was actually read.
    #[test]
    #[cfg(target_os = "linux")]
    fn reports_nothing_where_there_is_nothing() {
        let dir = TempDir::new().unwrap();

        let found = detect(&env_for(dir.path()));

        assert!(!found.available);
        assert!(found.palette.is_none());
        assert_eq!(found.reason.as_deref(), Some("Omarchy was not detected"));
    }

    /// Installed but unreadable is a different sentence from not installed, and
    /// only one of them is worth putting in front of anybody.
    #[test]
    #[cfg(target_os = "linux")]
    fn tells_an_unreadable_palette_from_an_absent_one() {
        let dir = TempDir::new().unwrap();
        install(dir.path(), "broken", "mode = \"dark\"\n");

        let found = detect(&env_for(dir.path()));

        assert!(!found.available);
        assert_eq!(
            found.reason.as_deref(),
            Some("Omarchy is installed but its active palette could not be read")
        );
    }

    /// The older layout has no `theme.name`; the `current/theme` symlink is
    /// what names the theme there.
    #[test]
    #[cfg(target_os = "linux")]
    fn reads_the_legacy_layout_and_takes_its_name_from_the_link() {
        let dir = TempDir::new().unwrap();
        let themes = dir.path().join(".config/omarchy/themes/nord");
        fs::create_dir_all(&themes).unwrap();
        fs::write(themes.join("colors.toml"), REAL).unwrap();

        let current = dir.path().join(".config/omarchy/current");
        fs::create_dir_all(&current).unwrap();
        std::os::unix::fs::symlink(&themes, current.join("theme")).unwrap();

        let found = detect(&env_for(dir.path()));

        assert!(found.available);
        assert_eq!(found.layout, Some(Layout::Legacy));
        assert_eq!(found.name.as_deref(), Some("nord"));
    }

    /// The state layout wins where both exist. An installation that has been
    /// upgraded keeps the old directory around, and following the stale one
    /// would mean Spagitty tracking a theme nothing else on the machine uses.
    #[test]
    #[cfg(target_os = "linux")]
    fn prefers_the_state_layout_over_the_legacy_one() {
        let dir = TempDir::new().unwrap();
        install(dir.path(), "current-one", REAL);

        let legacy = dir.path().join(".config/omarchy/current/theme");
        fs::create_dir_all(&legacy).unwrap();
        fs::write(
            legacy.join("colors.toml"),
            "background = \"#ffffff\"\nforeground = \"#000000\"\n",
        )
        .unwrap();

        let found = detect(&env_for(dir.path()));

        assert_eq!(found.layout, Some(Layout::State));
        assert_eq!(found.palette.unwrap().background, "#191724");
    }

    /// The directory is replaced wholesale by `omarchy-theme-set`, so the
    /// answer has to come from the path each time rather than from anything
    /// cached against an inode.
    #[test]
    #[cfg(target_os = "linux")]
    fn follows_the_directory_being_replaced() {
        let dir = TempDir::new().unwrap();
        install(dir.path(), "first", REAL);
        let env = env_for(dir.path());
        assert_eq!(detect(&env).palette.unwrap().background, "#191724");

        // What the script does: build the next one beside it, then swap.
        let current = dir.path().join(".local/state/omarchy/current");
        let next = current.join("next-theme");
        fs::create_dir_all(&next).unwrap();
        fs::write(
            next.join("colors.toml"),
            "mode = \"light\"\nbackground = \"#faf4ed\"\nforeground = \"#575279\"\n",
        )
        .unwrap();
        fs::remove_dir_all(current.join("theme")).unwrap();
        fs::rename(&next, current.join("theme")).unwrap();
        fs::write(current.join("theme.name"), "rose-pine-dawn\n").unwrap();

        let found = detect(&env);
        assert_eq!(found.name.as_deref(), Some("rose-pine-dawn"));
        assert_eq!(found.palette.unwrap().background, "#faf4ed");
    }

    /// A name is a label in a settings screen. Anything that looks like a path
    /// is refused rather than rendered.
    #[test]
    #[cfg(target_os = "linux")]
    fn refuses_a_name_that_is_not_a_name() {
        let dir = TempDir::new().unwrap();
        install(dir.path(), "../../etc/passwd", REAL);

        assert_eq!(detect(&env_for(dir.path())).name, None);
    }

    /// A fifo, a directory, or something enormous where a palette should be.
    #[test]
    #[cfg(target_os = "linux")]
    fn refuses_a_palette_that_is_not_a_bounded_file() {
        let dir = TempDir::new().unwrap();
        let theme = dir.path().join(".local/state/omarchy/current/theme");
        fs::create_dir_all(theme.join("colors.toml")).unwrap();

        assert!(!detect(&env_for(dir.path())).available);
    }
}
